// Stub: Chat module migrated to Convex (v3)
export const store = {
  saveMessage: async (_msg?: any) => {},
  getMessages: async (_agentId?: string, _limit?: number) => [],
  getConversation: async (_agentId?: string, _userId?: string) => ({ messages: [] }),
  registerAgent: async (_agent?: any) => {},
  getAgent: async (_agentId?: string) => null,
  getAllAgents: async () => [],
  updateAgentStatus: async (_agentId?: string, _status?: string) => {},
  heartbeat: async (_agentId?: string) => {},
  getTeamMessages: async (_limit?: number) => [],
  saveTeamMessage: async (_msg?: any) => {},
  getOnlineAgentCount: () => 0,
  getAllMessages: async (_limit?: number) => [],
  getBroadcastMessages: async (_limit?: number) => [],
  getConversations: async (_agentId?: string) => [],
  addMessage: async (_msg?: any) => {},
  removeAgent: async (_agentId?: string) => {},
  getGroupChatMessages: async (_groupId?: string, _since?: number) => [],
};
